name: pkgcheck

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-RedundantVersion,-NonsolvableDepsInDev
      - name: Inform on IRC
        if: ${{ failure() && github.repository == 'gentoo/guru' && github.event_name != 'pull_request' }}
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#gentoo-guru"
          server: "irc.libera.chat"
          nickname: "github-ci"
          message: CI failure detected on job ${{ github.workflow }} - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
